version: '3.3'

networks:
  devnet:
    driver: bridge

services:

  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    networks:
      - devnet
    ports:
      - 27017:27017
  # mongo-db-express:
  #   container_name: mongo-db-express
  #   image: mongo-express
  #   restart: always
  #   networks: 
  #     - devnet
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
